### ISSUE TITLE
Build Fail On Platform Add and Build IOS

### ISSUE THREAD

**Issue by noblesm19** [tableau/mobile-app-bootstrap-cordova#13]
First `$ ionic cordova platform add ios` command results in:

LUSC02VT0NSHTDH:mobile-app-bootstrap-cordova-master snobles$ ionic cordova platform add ios

? Looks like a fresh checkout! No ./node_modules directory found. Would you like
 to install project dependencies? Yes
Installing dependencies may take several minutes!
> npm i
✔ Running command - done!
> cordova platform add ios --save
Using cordova-fetch for cordova-ios@~4.5.1

(node:26112) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch platform cordova-ios@~4.5.1
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Failed to get absolute path to installed module
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/platform/addHelper.js:312:25
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:808:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:112:11)
(node:26112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Second pass results in:

LUSC02VT0NSHTDH:mobile-app-bootstrap-cordova-master snobles$ ionic cordova platform add ios
> cordova platform add ios --save
Using cordova-fetch for cordova-ios@4.5.4

Adding ios project...

Creating Cordova project for the iOS platform:
	Path: ../../desktop/mobile-app-bootstrap-cordova-master/platforms/ios
	Package: com.ionicframework.tableausampleapp703296
	Name: TableauSampleApp
iOS project created with cordova-ios@4.5.4
Installing "cordova-plugin-device" for ios
Installing "cordova-plugin-device-orientation" for ios
Installing "cordova-plugin-inappbrowser" for ios
Installing "cordova-plugin-splashscreen" for ios
Installing "cordova-plugin-statusbar" for ios

Installing "cordova-plugin-whitelist" for ios

Installing "ionic-plugin-keyboard" for ios
Discovered plugin "tableau-mobile-connected-client" in config.xml. Adding it to the project

Installing "tableau-plugin-oauth" for ios

Adding tableau-plugin-oauth to package.json
Saved plugin info for "tableau-plugin-oauth" to config.xml

Running command: /Users/snobles/desktop/mobile-app-bootstrap-cordova-master/hooks/after_prepare/010_add_platform_class.js /Users/snobles/desktop/mobile-app-bootstrap-cordova-master

add to body class: platform-ios
--save flag or autosave detected
Saving ios@~4.5.4 into config.xml file ...

After, running `$ ionic cordova build ios` results in:

[WARN] Not performing Ionic build for project type: ionic1.
> cordova build ios
Discovered plugin "tableau-mobile-connected-client" in config.xml. Adding it to the project

Failed to restore plugin "tableau-mobile-connected-client" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin git+https://github.com/tableau/mobile-connected-client.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
....
** BUILD SUCCEEDED **

[ERROR] An error occurred while running cordova build ios (exit code 1).

**Comment by Dat-gio** [comment]
did you get a resolution to the problem?

**Comment by brendankelleher01** [comment]
was there a resolution to this problem?
